tasks:
  - init: >
      yarn &&
      yarn setup &&
      yarn server
    openMode: split-right
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - Prisma.prisma
    - rangav.vscode-thunder-client